# Generated by Django 4.1.3 on 2022-12-23 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LOPHOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TENLOP', models.CharField(max_length=30)),
                ('SISO', models.IntegerField()),
                ('NIENKHOA', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='HocSinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HOTEN', models.CharField(max_length=300)),
                ('NGAYSINH', models.DateField()),
                ('EMAIL', models.CharField(max_length=30)),
                ('LOPHOC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.lophoc')),
            ],
        ),
    ]
