# Generated by Django 4.1.3 on 2022-12-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hocsinh',
            name='LOPHOC',
        ),
        migrations.AddField(
            model_name='hocsinh',
            name='LOPHOC',
            field=models.ManyToManyField(blank=True, to='base.lophoc'),
        ),
    ]
