# Generated by Django 4.1.3 on 2022-12-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_hocsinh_lophoc_hocsinh_lophoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='hocsinh',
            name='GIOITINH',
            field=models.CharField(blank=True, choices=[('M', 'male'), ('F', 'female')], max_length=5),
        ),
    ]
