# Generated by Django 4.1.3 on 2022-12-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_hocsinh_gioitinh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hocsinh',
            name='GIOITINH',
            field=models.CharField(blank=True, choices=[('M', 'male'), ('F', 'female')], max_length=5, null=True),
        ),
    ]
