# Generated by Django 4.1.4 on 2022-12-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_hocsinh_gioitinh'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=200, unique=True)),
                ('max_age', models.IntegerField()),
                ('min_age', models.IntegerField()),
            ],
        ),
    ]
