# Generated by Django 4.1.3 on 2023-01-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_monhoc_alter_lophoc_nienkhoa_alter_lophoc_siso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lophoc',
            name='NIENKHOA',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='lophoc',
            name='SISO',
            field=models.IntegerField(),
        ),
    ]
