# Generated by Django 4.1.3 on 2023-01-05 17:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_subject_alter_grade_subject_delete_monhoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='DIEMCHUAN',
            field=models.FloatField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
