# Generated by Django 4.1.3 on 2023-01-05 18:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_subject_diemchuan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lophoc',
            name='NIENKHOA',
            field=models.ForeignKey(max_length=10, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.age'),
        ),
        migrations.AlterField(
            model_name='lophoc',
            name='SISO',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
