# Generated by Django 4.1.3 on 2023-01-05 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_lophoc_nienkhoa_alter_lophoc_siso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lophoc',
            name='NIENKHOA',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.age'),
        ),
    ]
