# Generated by Django 4.1.3 on 2023-01-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_lophoc_nienkhoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hocsinh',
            name='EMAIL',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
